.PHONY: build-local up-local down-local test-local

define generate_env
	@cat ../src/config/toml/env.toml > .env.tmp
	@cat ../src/config/toml/env.$(1).toml >> .env.tmp 2>/dev/null || true
	@cat ../src/config/toml/env.$(1).local.toml >> .env.tmp 2>/dev/null || true

	@if [ "$(1)" = "local" ]; then \
		cat ../src/config/toml/env.development.local.toml >> .env.tmp 2>/dev/null || true; \
		cat ../src/config/toml/env.qa.local.toml >> .env.tmp 2>/dev/null || true; \
		cat ../src/config/toml/env.production.local.toml >> .env.tmp 2>/dev/null || true; \
	fi

	@awk -F= '!/^#/ && !/^$$/ {sub(/#.*$$/, ""); gsub(/^[ \t]+|[ \t]+$$/, ""); if($$0) print}' .env.tmp | \
	 awk '{lines[NR]=$$0} END {for(i=NR;i>0;i--) print lines[i]}' | \
	 awk -F= '!seen[$$1]++' | \
	 awk '{lines[NR]=$$0} END {for(i=NR;i>0;i--) print lines[i]}' > .env
	@rm -f .env.tmp
endef

build-local:
	$(call generate_env,local)
	@docker compose -f local.yaml build

up-local:
	$(call generate_env,local)
	@docker compose --env-file .env -f local.yaml up -d

down-local:
	@docker compose -f local.yaml down && \
	rm -f .env

test-local:
	  @docker exec -it {{ project_name }}_app_local sh -c "pytest ."