name: CI

on:
  push:
  pull_request:


jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  audit:
    needs: [ lint ]
    uses: ./.github/workflows/audit.yml

  tests:
    needs: [ lint ]
    uses: ./.github/workflows/tests.yml
