name: Tests

on:
  workflow_call:

jobs:
  tests:
    name: Test with Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --group test

      - name: Run tests
        run: |
          uv run pytest

      - name: Upload coverage reports to Codecov
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hmarcuzzo/fastgear-cli
